using System.Collections.Generic;

namespace SysBot.Pokemon;

public static class DmaxPokemonData
{
    public struct DmaxAdventureTemplate
    {
        public ushort species;
        public byte altForm;
        public bool isBoss;
        public int abilityIndex;

        public DmaxAdventureTemplate(ushort Species, byte altform, bool isboss, int abilityindex)
        {
            species = Species;
            altForm = altform;
            isBoss = isboss;
            abilityIndex = abilityindex;
        }
    };

    public static List<DmaxAdventureTemplate> dmaxAdventureTemplates = new List<DmaxAdventureTemplate>()
    {  new DmaxAdventureTemplate( 2, 0, false, 2 ),  new DmaxAdventureTemplate( 5, 0, false, 2 ),
   new DmaxAdventureTemplate( 8, 0, false, 2 ),  new DmaxAdventureTemplate( 12, 0, false, 2 ),
   new DmaxAdventureTemplate( 26, 0, false, 2 ), new DmaxAdventureTemplate( 26, 1, false, 1 ),
   new DmaxAdventureTemplate( 28, 0, false, 2 ), new DmaxAdventureTemplate( 28, 1, false, 1 ),
   new DmaxAdventureTemplate( 31, 0, false, 0 ), new DmaxAdventureTemplate( 34, 0, false, 1 ),
   new DmaxAdventureTemplate( 35, 0, false , 2), new DmaxAdventureTemplate( 737, 0, false, 1 ),
   new DmaxAdventureTemplate( 743, 0, false, 2 ),new DmaxAdventureTemplate( 40, 0, false, 2 ),
   new DmaxAdventureTemplate( 553, 0, false, 2 ),new DmaxAdventureTemplate( 45, 0, false, 2 ),
   new DmaxAdventureTemplate( 51, 0, false, 2 ), new DmaxAdventureTemplate( 51, 1, false , 0),
   new DmaxAdventureTemplate( 53, 0, false , 1), new DmaxAdventureTemplate( 53, 1, false, 0 ),
   new DmaxAdventureTemplate( 55, 0, false, 2 ), new DmaxAdventureTemplate( 62, 0, false, 0 ),
   new DmaxAdventureTemplate( 64, 0, false , 2 ), new DmaxAdventureTemplate( 67, 0, false, 1 ),
   new DmaxAdventureTemplate( 745, 0, false, 1 ),new DmaxAdventureTemplate( 745, 1, false, 2 ),
   new DmaxAdventureTemplate( 82, 0, false, 2 ), new DmaxAdventureTemplate( 752, 0, false, 2 ),
   new DmaxAdventureTemplate( 754, 0, false, 2 ),new DmaxAdventureTemplate( 93, 0, false, 1 ),
   new DmaxAdventureTemplate( 869, 0, false, 2 ),new DmaxAdventureTemplate( 99, 0, false, 0 ),
   new DmaxAdventureTemplate( 105, 0, false, 2 ),new DmaxAdventureTemplate( 105, 1, false, 2 ),
   new DmaxAdventureTemplate( 106, 0, false, 0 ),new DmaxAdventureTemplate( 107, 0, false, 1 ),
   new DmaxAdventureTemplate( 108, 0, false, 0 ),new DmaxAdventureTemplate( 110, 0, false, 1 ),
   new DmaxAdventureTemplate( 110, 1, false, 2 ),new DmaxAdventureTemplate( 112, 0, false, 1 ),
   new DmaxAdventureTemplate( 113, 0, false, 2 ),new DmaxAdventureTemplate( 114, 0, false, 1 ),
   new DmaxAdventureTemplate( 115, 0, false, 0 ),new DmaxAdventureTemplate( 117, 0, false, 1 ),
   new DmaxAdventureTemplate( 119, 0, false, 2 ),new DmaxAdventureTemplate( 122, 0, false, 1 ),
   new DmaxAdventureTemplate( 122, 1, false, 2 ),new DmaxAdventureTemplate( 123, 0, false, 1 ),
   new DmaxAdventureTemplate( 124, 0, false, 2 ),new DmaxAdventureTemplate( 125, 0, false, 2 ),
   new DmaxAdventureTemplate( 126, 0, false, 2 ),new DmaxAdventureTemplate( 756, 0, false, 2 ),
   new DmaxAdventureTemplate( 128, 0, false, 2 ),new DmaxAdventureTemplate( 148, 0, false, 2 ),
   new DmaxAdventureTemplate( 164, 0, false, 2 ),new DmaxAdventureTemplate( 171, 0, false, 2 ),
   new DmaxAdventureTemplate( 176, 0, false, 2 ),new DmaxAdventureTemplate( 178, 0, false, 2 ),
   new DmaxAdventureTemplate( 182, 0, false, 2 ),new DmaxAdventureTemplate( 184, 0, false, 2 ),
   new DmaxAdventureTemplate( 185, 0, false, 2 ),new DmaxAdventureTemplate( 186, 0, false, 2 ),
   new DmaxAdventureTemplate( 195, 0, false, 2 ),new DmaxAdventureTemplate( 206, 0, false, 2 ),
   new DmaxAdventureTemplate( 211, 0, false, 2 ),new DmaxAdventureTemplate( 758, 0, false, 2 ),
   new DmaxAdventureTemplate( 215, 0, false, 2 ),new DmaxAdventureTemplate( 221, 0, false, 2 ),
   new DmaxAdventureTemplate( 760, 0, false, 2 ),new DmaxAdventureTemplate( 763, 0, false, 2 ),
   new DmaxAdventureTemplate( 224, 0, false, 2 ),new DmaxAdventureTemplate( 226, 0, false, 2 ),
   new DmaxAdventureTemplate( 227, 0, false, 2 ),new DmaxAdventureTemplate( 237, 0, false, 2 ),
   new DmaxAdventureTemplate( 241, 0, false, 2 ),new DmaxAdventureTemplate( 764, 0, false, 2 ),
   new DmaxAdventureTemplate( 264, 0, false, 2 ),new DmaxAdventureTemplate( 264, 1, false, 2 ),
   new DmaxAdventureTemplate( 103, 0, false, 2 ),new DmaxAdventureTemplate( 405, 0, false, 2 ),
   new DmaxAdventureTemplate( 279, 0, false, 2 ),new DmaxAdventureTemplate( 291, 0, false, 2 ),
   new DmaxAdventureTemplate( 295, 0, false, 2 ),new DmaxAdventureTemplate( 770, 0, false, 2 ),
   new DmaxAdventureTemplate( 771, 0, false, 2 ),new DmaxAdventureTemplate( 305, 0, false, 2 ),
   new DmaxAdventureTemplate( 310, 0, false, 2 ),new DmaxAdventureTemplate( 315, 0, false, 2 ),
   new DmaxAdventureTemplate( 319, 0, false, 2 ),new DmaxAdventureTemplate( 320, 0, false, 2 ),
   new DmaxAdventureTemplate( 324, 0, false, 2 ),new DmaxAdventureTemplate( 862, 0, false, 2 ),
   new DmaxAdventureTemplate( 334, 0, false, 2 ),new DmaxAdventureTemplate( 844, 0, false, 2 ),
   new DmaxAdventureTemplate( 858, 0, false, 2 ),new DmaxAdventureTemplate( 340, 0, false, 2 ),
   new DmaxAdventureTemplate( 342, 0, false, 2 ),new DmaxAdventureTemplate( 344, 0, false, 2 ),
   new DmaxAdventureTemplate( 356, 0, false, 2 ),new DmaxAdventureTemplate( 359, 0, false, 2 ),
   new DmaxAdventureTemplate( 362, 0, false, 2 ),new DmaxAdventureTemplate( 364, 0, false, 2 ),
   new DmaxAdventureTemplate( 369, 0, false, 2 ),new DmaxAdventureTemplate( 132, 0, false, 2 ),
   new DmaxAdventureTemplate( 375, 0, false, 2 ),new DmaxAdventureTemplate( 416, 0, false, 2 ),
   new DmaxAdventureTemplate( 421, 0, false, 2 ),new DmaxAdventureTemplate( 423, 1, false, 2 ),
   new DmaxAdventureTemplate( 426, 0, false, 2 ),new DmaxAdventureTemplate( 428, 0, false, 2 ),
   new DmaxAdventureTemplate( 435, 0, false, 2 ),new DmaxAdventureTemplate( 537, 0, false, 2 ),
   new DmaxAdventureTemplate( 452, 0, false, 2 ),new DmaxAdventureTemplate( 777, 0, false, 2 ),
   new DmaxAdventureTemplate( 460, 0, false, 2 ),new DmaxAdventureTemplate( 478, 0, false, 2 ),
   new DmaxAdventureTemplate( 479, 0, false, 2 ),new DmaxAdventureTemplate( 508, 0, false, 2 ),
   new DmaxAdventureTemplate( 510, 0, false, 2 ),new DmaxAdventureTemplate( 518, 0, false, 2 ),
   new DmaxAdventureTemplate( 521, 0, false, 2 ),new DmaxAdventureTemplate( 528, 0, false, 2 ),
   new DmaxAdventureTemplate( 531, 0, false, 2 ),new DmaxAdventureTemplate( 533, 0, false, 2 ),
   new DmaxAdventureTemplate( 536, 0, false, 2 ),new DmaxAdventureTemplate( 778, 0, false, 2 ),
   new DmaxAdventureTemplate( 884, 0, false, 2 ),new DmaxAdventureTemplate( 545, 0, false, 2 ),
   new DmaxAdventureTemplate( 547, 0, false, 2 ),new DmaxAdventureTemplate( 549, 0, false, 2 ),
   new DmaxAdventureTemplate( 550, 0, false, 2 ),new DmaxAdventureTemplate( 550, 1, false, 2 ),
   new DmaxAdventureTemplate( 828, 0, false, 2 ),new DmaxAdventureTemplate( 834, 0, false, 2 ),
   new DmaxAdventureTemplate( 556, 0, false, 2 ),new DmaxAdventureTemplate( 558, 0, false, 2 ),
   new DmaxAdventureTemplate( 830, 0, false, 2 ),new DmaxAdventureTemplate( 561, 0, false, 2 ),
   new DmaxAdventureTemplate( 446, 0, false, 2 ),new DmaxAdventureTemplate( 855, 0, false, 2 ),
   new DmaxAdventureTemplate( 569, 0, false, 2 ),new DmaxAdventureTemplate( 573, 0, false, 2 ),
   new DmaxAdventureTemplate( 836, 0, false, 2 ),new DmaxAdventureTemplate( 820, 0, false, 2 ),
   new DmaxAdventureTemplate( 583, 0, false, 2 ),new DmaxAdventureTemplate( 587, 0, false, 2 ),
   new DmaxAdventureTemplate( 589, 0, false, 2 ),new DmaxAdventureTemplate( 591, 0, false, 2 ),
   new DmaxAdventureTemplate( 593, 0, false, 2 ),new DmaxAdventureTemplate( 596, 0, false, 2 ),
   new DmaxAdventureTemplate( 601, 0, false, 2 ),new DmaxAdventureTemplate( 606, 0, false, 2 ),
   new DmaxAdventureTemplate( 608, 0, false, 2 ),new DmaxAdventureTemplate( 611, 0, false, 2 ),
   new DmaxAdventureTemplate( 614, 0, false, 2 ),new DmaxAdventureTemplate( 615, 0, false, 2 ),
   new DmaxAdventureTemplate( 617, 0, false, 2 ),new DmaxAdventureTemplate( 618, 0, false, 2 ),
   new DmaxAdventureTemplate( 618, 1, false, 2 ),new DmaxAdventureTemplate( 621, 0, false, 2 ),
   new DmaxAdventureTemplate( 623, 0, false, 2 ),new DmaxAdventureTemplate( 625, 0, false, 2 ),
   new DmaxAdventureTemplate( 626, 0, false, 2 ),new DmaxAdventureTemplate( 631, 0, false, 2 ),
   new DmaxAdventureTemplate( 632, 0, false, 2 ),new DmaxAdventureTemplate( 832, 0, false, 2 ),
   new DmaxAdventureTemplate( 660, 0, false, 2 ),new DmaxAdventureTemplate( 663, 0, false, 2 ),
   new DmaxAdventureTemplate( 675, 0, false, 2 ),new DmaxAdventureTemplate( 39, 0, false, 2 ),
   new DmaxAdventureTemplate( 525, 0, false, 2 ),new DmaxAdventureTemplate( 680, 0, false, 2 ),
   new DmaxAdventureTemplate( 687, 0, false, 2 ),new DmaxAdventureTemplate( 689, 0, false, 2 ),
   new DmaxAdventureTemplate( 695, 0, false, 2 ),new DmaxAdventureTemplate( 702, 0, false, 2 ),
   new DmaxAdventureTemplate( 851, 0, false, 2 ),new DmaxAdventureTemplate( 707, 0, false, 2 ),
   new DmaxAdventureTemplate( 709, 0, false, 2 ),new DmaxAdventureTemplate( 711, 0, false, 2 ),
   new DmaxAdventureTemplate( 847, 0, false, 2 ),new DmaxAdventureTemplate( 845, 0, false, 2 ),
   new DmaxAdventureTemplate( 620, 0, false, 2 ),new DmaxAdventureTemplate( 870, 0, false, 2 ),
   new DmaxAdventureTemplate( 701, 0, false, 2 ),new DmaxAdventureTemplate( 879, 0, false, 2 ),
   new DmaxAdventureTemplate( 826, 0, false, 2 ),new DmaxAdventureTemplate( 838, 0, false, 2 ),
   new DmaxAdventureTemplate( 877, 0, false, 2 ),new DmaxAdventureTemplate( 563, 0, false, 2 ),
   new DmaxAdventureTemplate( 750, 0, false, 2 ),new DmaxAdventureTemplate( 863, 0, false, 2 ),
   new DmaxAdventureTemplate( 871, 0, false, 2 ),new DmaxAdventureTemplate( 873, 0, false, 2 ),
   new DmaxAdventureTemplate( 839, 0, false, 2 ),new DmaxAdventureTemplate( 853, 0, false, 2 ),
   new DmaxAdventureTemplate( 861, 0, false, 2 ),new DmaxAdventureTemplate( 886, 0, false, 2 ),
   new DmaxAdventureTemplate( 36, 0, false, 2 ), new DmaxAdventureTemplate( 44, 0, false, 2 ),
   new DmaxAdventureTemplate( 137, 0, false, 2 ),new DmaxAdventureTemplate( 600, 0, false, 2 ),
   new DmaxAdventureTemplate( 738, 0, false, 2 ),new DmaxAdventureTemplate( 254, 0, false, 2 ),
   new DmaxAdventureTemplate( 257, 0, false, 2 ),new DmaxAdventureTemplate( 260, 0, false, 2 ),
   new DmaxAdventureTemplate( 73, 0, false, 2 ), new DmaxAdventureTemplate( 80, 0, false, 2 ),
   new DmaxAdventureTemplate( 121, 0, false, 2 ),new DmaxAdventureTemplate( 849, 0, false, 2 ),
   new DmaxAdventureTemplate( 134, 0, false, 2 ),new DmaxAdventureTemplate( 135, 0, false, 2 ),
   new DmaxAdventureTemplate( 136, 0, false, 2 ),new DmaxAdventureTemplate( 199, 0, false, 2 ),
   new DmaxAdventureTemplate( 330, 0, false, 2 ),new DmaxAdventureTemplate( 346, 0, false, 2 ),
   new DmaxAdventureTemplate( 348, 0, false, 2 ),new DmaxAdventureTemplate( 437, 0, false, 2 ),
   new DmaxAdventureTemplate( 697, 0, false, 2 ),new DmaxAdventureTemplate( 253, 0, false, 2 ),
   new DmaxAdventureTemplate( 256, 0, false, 2 ),new DmaxAdventureTemplate( 259, 0, false, 2 ),
   new DmaxAdventureTemplate( 699, 0, false, 2 ),new DmaxAdventureTemplate( 765, 0, false, 2 ),
   new DmaxAdventureTemplate( 766, 0, false, 2 ),new DmaxAdventureTemplate( 876, 0, false, 2 ),
   new DmaxAdventureTemplate( 145, 0, true, 1 ), new DmaxAdventureTemplate( 146, 0, true, 1 ),
   new DmaxAdventureTemplate( 144, 0, true, 1 ), new DmaxAdventureTemplate( 150, 0, true, 1 ),
   new DmaxAdventureTemplate( 245, 0, true, 1 ), new DmaxAdventureTemplate( 244, 0, true, 1 ),
   new DmaxAdventureTemplate( 243, 0, true, 1 ), new DmaxAdventureTemplate( 249, 0, true, 1 ),
   new DmaxAdventureTemplate( 250, 0, true, 1 ), new DmaxAdventureTemplate( 380, 0, true, 1 ),
   new DmaxAdventureTemplate( 381, 0, true, 1 ), new DmaxAdventureTemplate( 383, 0, true, 1 ),
   new DmaxAdventureTemplate( 382, 0, true, 1 ), new DmaxAdventureTemplate( 384, 0, true, 1 ),
   new DmaxAdventureTemplate( 480, 0, true, 1 ), new DmaxAdventureTemplate( 482, 0, true, 1 ),
   new DmaxAdventureTemplate( 481, 0, true, 1 ), new DmaxAdventureTemplate( 483, 0, true, 1 ),
   new DmaxAdventureTemplate( 484, 0, true, 1 ), new DmaxAdventureTemplate( 487, 0, true, 1 ),
   new DmaxAdventureTemplate( 485, 0, true, 1 ), new DmaxAdventureTemplate( 488, 0, true, 1 ),
   new DmaxAdventureTemplate( 641, 0, true, 1 ), new DmaxAdventureTemplate( 642, 0, true, 1 ),
   new DmaxAdventureTemplate( 645, 0, true, 1 ), new DmaxAdventureTemplate( 643, 0, true, 1 ),
   new DmaxAdventureTemplate( 644, 0, true, 1 ), new DmaxAdventureTemplate( 646, 0, true, 1 ),
   new DmaxAdventureTemplate( 716, 0, true, 1 ), new DmaxAdventureTemplate( 717, 0, true, 1 ),
   new DmaxAdventureTemplate( 718, 3, true, 1 ), new DmaxAdventureTemplate( 785, 0, true, 1 ),
   new DmaxAdventureTemplate( 786, 0, true, 1 ), new DmaxAdventureTemplate( 787, 0, true, 1 ),
   new DmaxAdventureTemplate( 788, 0, true, 1 ), new DmaxAdventureTemplate( 791, 0, true, 1 ),
   new DmaxAdventureTemplate( 792, 0, true, 1 ), new DmaxAdventureTemplate( 800, 0, true, 1 ),
   new DmaxAdventureTemplate( 793, 0, true, 1 ), new DmaxAdventureTemplate( 794, 0, true, 1 ),
   new DmaxAdventureTemplate( 795, 0, true, 1 ), new DmaxAdventureTemplate( 796, 0, true, 1 ),
   new DmaxAdventureTemplate( 798, 0, true, 1 ), new DmaxAdventureTemplate( 797, 0, true, 1 ),
   new DmaxAdventureTemplate( 799, 0, true, 1 ), new DmaxAdventureTemplate( 806, 0, true, 1 ),
   new DmaxAdventureTemplate( 805, 0, true, 1 )
    };
}
public enum LairSpecies : ushort
{
    None = 0,
    Zapdos = 145,
    Moltres = 146,
    Articuno = 144,
    Mewtwo = 150,
    Suicune = 245,
    Entei = 244,
    Raikou = 243,
    Lugia = 249,
    HoOh = 250,
    Latias = 380,
    Latios = 381,
    Groudon = 383,
    Kyogre = 382,
    Rayquaza = 384,
    Uxie = 480,
    Azelf = 482,
    Mesprit = 481,
    Dialga = 483,
    Palkia = 484,
    Giratina = 487,
    Heatran = 485,
    Cresselia = 488,
    Tornadus = 641,
    Thundurus = 642,
    Landorus = 645,
    Reshiram = 643,
    Zekrom = 644,
    Kyurem = 646,
    Xerneas = 716,
    Yveltal = 717,
    Zygarde = 718,
    TapuKoko = 785,
    TapuLele = 786,
    TapuBulu = 787,
    TapuFini = 788,
    Solgaleo = 791,
    Lunala = 792,
    Necrozma = 800,
    Nihilego = 793,
    Buzzwole = 794,
    Pheromosa = 795,
    Xurkitree = 796,
    Kartana = 798,
    Celesteela = 797,
    Guzzlord = 799,
    Blacephalon = 806,
    Stakataka = 805
}
public enum LairSpeciesSW : ushort
{
    HoOh = 250,
    Latios = 381,
    Groudon = 383,
    Dialga = 483,
    Tornadus = 641,
    Reshiram = 643,
    Xerneas = 716,
    Solgaleo = 791,
}
public enum LairSpeciesSH : ushort
{
    Lugia = 249,
    Latias = 380,
    Kyogre = 382,
    Palkia = 484,
    Thundurus = 642,
    Zekrom = 644,
    Yveltal = 717,
    Lunala = 792,
}
public enum LairSpeciesBlock
{
    Zapdos,
    Moltres,
    Articuno,
    Mewtwo,
    Suicune,
    Entei,
    Raikou,
    Lugia,
    HoOh,
    Latias,
    Latios,
    Groudon,
    Kyogre,
    Rayquaza,
    Uxie,
    Azelf,
    Mesprit,
    Dialga,
    Palkia,
    Giratina,
    Heatran,
    Cresselia,
    Tornadus,
    Thundurus,
    Landorus,
    Reshiram,
    Zekrom,
    Kyurem,
    Xerneas,
    Yveltal,
    Zygarde,
    TapuKoko,
    TapuLele,
    TapuBulu,
    TapuFini,
    Solgaleo,
    Lunala,
    Necrozma,
    Nihilego,
    Buzzwole,
    Pheromosa,
    Xurkitree,
    Kartana,
    Celesteela,
    Guzzlord,
    Blacephalon,
    Stakataka
}

public enum SelectPath
{
    GoLeft,
    GoRight,
}

public enum PriorityMoves : ushort
{
    Accelerock = 709,
    FakeOut = 252,
    ExtremeSpeed = 245,
    Feint = 364,
    FirstImpression = 660,
    AquaJet = 453,
    BulletPunch = 418,
    IceShard = 420,
    MachPunch = 183,
    QuickAttack = 98,
    ShadowSneak = 425,
    SuckerPunch = 389,
    VacuumWave = 410,
    WaterShuriken = 594
}

public enum MoveCategory
{
    Status,
    Physical,
    Special
}

public enum StatusCondition
{
    NoCondition,
    Paralyzed,
    Asleep,
    Frozen,
    Burned,
    Poisoned,
}

public enum MoveTarget
{
    AllAdjacentOpponents,
    AllAdjacent,
    AllAllies,
    AllyOrSelf,
    Ally,
    AnyExceptSelf,
    Self,
    SideSelf,
    SideAll,
    Counter,
    All,
    Opponent,
    RandomOpponent,
}

public enum DmaxMoves
{
    MaxStrike,
    MaxKnuckle,
    MaxAirstream,
    MaxOoze,
    MaxQuake,
    MaxRockfall,
    MaxFlutterby,
    MaxPhantasm,
    MaxSteelspike,
    MaxFlare,
    MaxGeyser,
    MaxOvergrowth,
    MaxLightning,
    MaxMindstorm,
    MaxHailstorm,
    MaxWyrmwind,
    MaxDarkness,
    MaxStarfall,
    MaxGuard,
}

public enum LairBotModes
{
    OffsetLog,
    LairBot,
}

public enum LairBall : byte
{
    Master = 1,
    Ultra = 2,
    Great = 3,
    Poke = 4,
    Safari = 5,
    Net = 6,
    Dive = 7,
    Nest = 8,
    Repeat = 9,
    Timer = 10,
    Luxury = 11,
    Premier = 12,
    Dusk = 13,
    Heal = 14,
    Quick = 15,
    Cherish = 16,
    Fast = 17,
    Level = 18,
    Lure = 19,
    Heavy = 20,
    Love = 21,
    Friend = 22,
    Moon = 23,
    Sport = 24,
    Dream = 25,
    Beast = 26
}
