//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysBot.Pokemon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysBot.Pokemon.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;m_GameObject&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 0
        ///  },
        ///  &quot;m_Enabled&quot;: 1,
        ///  &quot;m_Script&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 5036064567846753479
        ///  },
        ///  &quot;m_Name&quot;: &quot;FieldEncountTable_d&quot;,
        ///  &quot;table&quot;: [
        ///    {
        ///      &quot;zoneID&quot;: 24,
        ///      &quot;encRate_gr&quot;: 0,
        ///      &quot;ground_mons&quot;: [
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FieldEncountTable_d {
            get {
                return ResourceManager.GetString("FieldEncountTable_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;m_GameObject&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 0
        ///  },
        ///  &quot;m_Enabled&quot;: 1,
        ///  &quot;m_Script&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 5036064567846753479
        ///  },
        ///  &quot;m_Name&quot;: &quot;FieldEncountTable_p&quot;,
        ///  &quot;table&quot;: [
        ///    {
        ///      &quot;zoneID&quot;: 24,
        ///      &quot;encRate_gr&quot;: 0,
        ///      &quot;ground_mons&quot;: [
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FieldEncountTable_p {
            get {
                return ResourceManager.GetString("FieldEncountTable_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GigantamaxIcon {
            get {
                object obj = ResourceManager.GetObject("GigantamaxIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Canalave City
        ///Canalave City
        ///Canalave Gym
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Can [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_bdsp_00000_en {
            get {
                return ResourceManager.GetString("text_bdsp_00000_en", resourceCulture);
            }
        }
    }
}
